#!/bin/bash

clear
sleep 2
echo -n "\033[32m[+]\033[0m Setting up storage permissions.."
yes | termux-setup-storage &>/dev/null
sleep 2
clear
while true; do
    if [ -d ~/storage/shared ]; then
        break
    else
        echo "Storage permission denied"
    fi
done
clear
sleep 2

echo -n "\033[32m[+]\033[0m  Installing Termux-am.."
pkg install termux-am -y &>/dev/null
echo -n "\033[34m[✓]\033[0m Termux-am Installed Successfuly "
echo -e "\n"

rm ~/x

if [ -e $PREFIX/glibc ]; then
    echo -n "Removing previous glibc. Continue? (Y/n) "
    read i
    if [ "$i" = "Y" ] || [ "$i" = "y" ]; then
        rm -rf $PREFIX/glibc
    else
        return 1
    fi
fi

INSTALL_WOW64=0

echo "Select an option"
echo "1) Install boxvidra with box86 build"
echo "2) Install boxvidra with wow64 build"
echo ""
echo -n "Selected number: "
read i
case "$i" in
1)
    INSTALL_WOW64=0
;;
2)
    INSTALL_WOW64=1
;;
*)
    return 1
;;
esac

echo "Installing boxvidra..."

function wget-git-q {
    wget -q --retry-connrefused --tries=0 --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main" -O $2
    return $?
}

echo "Updating package manager"
mkdir -p $PREFIX/glibc/opt/package-manager/installed

if [ "$INSTALL_WOW64" = "1" ]; then
echo "PRIVATE_TOKEN=glpat-h5r7HjKoPKZPxmfg79xs
PROJECT_ID=54240888">$PREFIX/glibc/opt/package-manager/token
else
echo "PRIVATE_TOKEN=glpat-Xs4HfrCkMpbedkPycqzP
PROJECT_ID=52465323">$PREFIX/glibc/opt/package-manager/token
fi

. $PREFIX/glibc/opt/package-manager/token
if ! wget-git-q "package-manager" "$PREFIX/glibc/opt/package-manager/package-manager"; then
    echo "Download failed"
    return 1
fi
. $PREFIX/glibc/opt/package-manager/package-manager
sync-all

if [ "$INSTALL_WOW64" = "1" ]; then
sync-package wine-9.3-vanilla-wow64
else
sync-package wine-ge-custom-8-25
fi

ln -sf $PREFIX/glibc/opt/scripts/boxvidra $PREFIX/bin/boxvidra

echo "\033[32m[+]\033[0m Installing Boxvidra Emulator packages..."
apt-get clean
apt-get update >/dev/null 2>&1
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade >/dev/null 2>&1
pkg install x11-repo -y &>/dev/null
pkg install pulseaudio -y &>/dev/null
pkg install wget -y &>/dev/null
pkg install root-repo -y &>/dev/null
pkg install termux-x11-nightly -y &>/dev/null
pkg install x11-repo &>/dev/null
pkg install termux-x11-nightly &>/dev/null
pkg install pulseaudio &>/dev/null
pkg install xfce4 &>/dev/null
pkg install tur-repo &>/dev/null
pkg install xwayland -y &>/dev/null
pkg install xorg-xrandr -y &>/dev/null
pkg install p7zip -y &>/dev/null
pkg install patchelf -y &>/dev/null
pkg install ncurses-utils -y &>/dev/null
pkg install hashdeep -y &>/dev/null
echo -n "\033[34m[✓]\033[0m Boxvidra Emulator Packages Installed Successfuly"
echo -e "\n"

echo "\033[32m[+]\033[0m Installing Boxvidra Emulator Programs..."
pkg update && pkg upgrade &>/dev/null
pkg install chromium -y &>/dev/null
pkg install firefox -y &>/dev/null
pkg install vlc -y &>/dev/null
pkg install vlc-qt &>/dev/null
echo -n "\033[34m[✓]\033[0m Boxvidra Programs Installed Successfuly"
echo -n "\033[34m[✓]\033[0m Boxvidra Installed Successfuly"
echo -e "\n"
echo -n "\033[34m[✓]\033[0m Boxvidra Emulator Installed Successfuly"
echo "Type \"boxvidra\"" To Start