#!/bin/bash

# WIN 10 THEME
echo -n "Installing Windows 11 theme..."
# DOWNLOAD 
wget https://github.com/AGENT404TRD/BOXVIDRA-EMULATOR-BETA-/releases/download/Themes/Windows.11.tar.xz

# EXTRACT
tar -xf Windows.11.tar.xz

# CD / ENTER TO THE FILE
cd 'Windows 11'

# COPY 404
cp -r .icons /data/data/com.termux/files/home

# COPY 
cp -r icons/* /data/data/com.termux/files/usr/share/icons
cp -r .themes /data/data/com.termux/files/home
cp -r .config /data/data/com.termux/files/home
cp -r Wallpapers /data/data/com.termux/files/home

# BACK
cd ..

# DELETE
rm -r 'Windows 11'
rm Windows.11.tar.xz
echo -e "\n"

echo -n "Boxvidra Scripts Installed Successfuly"
echo -e "\n"
sleep 3
clear

echo -n "Boxvidra Emulator Installed Successfuly"
echo -e "\n"
echo "Type \"boxvidra\"" To Start

echo -n "Boxvidra Scripts Installed Successfuly"
echo -e "\n"
sleep 3
clear

echo -n "Boxvidra Emulator Installed Successfuly"
echo -e "\n"
echo "Type \"boxvidra\"" To Start
BOXVIDRA-EMULATOR-BETA-/install at main · AGENT404TRD/BOXVIDRA-EMULATOR-BETA-