#!/bin/bash

. $PREFIX/glibc/opt/package-manager/token
function wget-git-q {
	wget -q --retry-connrefused --tries=0 --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main" -O $2
	return $?
}
mv $PREFIX/glibc/opt/package-manager/package-manager $PREFIX/glibc/opt/package-manager/package-manager-bak 
wget-git-q "package-manager" "$PREFIX/glibc/opt/package-manager/package-manager"
if [ "$?" = "0" ]; then
	rm $PREFIX/glibc/opt/package-manager/package-manager-bak
	. $PREFIX/glibc/opt/package-manager/package-manager
	sync-all 
	sleep 2
else
	mv $PREFIX/glibc/opt/package-manager/package-manager-bak $PREFIX/glibc/opt/package-manager/package-manager
	echo "No Internet, Couldn't check for updates"
	sleep 1
	. $PREFIX/glibc/opt/package-manager/package-manager
fi

. $PREFIX/glibc/opt/scripts/boxvidra_menu
