#!/bin/bash

function load_package-manager {
	mv $PREFIX/glibc/opt/package-manager/package-manager $PREFIX/glibc/opt/package-manager/package-manager-bak 
	wget-git-q "package-manager" "$PREFIX/glibc/opt/package-manager/package-manager"
	if [ "$?" = "0" ]; then
		rm $PREFIX/glibc/opt/package-manager/package-manager-bak
		. $PREFIX/glibc/opt/package-manager/package-manager
		return 0
	else
		mv $PREFIX/glibc/opt/package-manager/package-manager-bak $PREFIX/glibc/opt/package-manager/package-manager
		echo "No internet connection"
		sleep 2
		return 1
	fi
}

function load_configs {
	cp -rn $PREFIX/glibc/opt/default-conf/* $PREFIX/glibc/opt &>/dev/null
	cp $PREFIX/glibc/opt/default-conf/conf/path.conf $PREFIX/glibc/opt/conf
	if [ "$(cat $PREFIX/glibc/opt/dxvk.conf 2>/dev/null)" = "" ]; then
		cp $PREFIX/glibc/opt/default-conf/dxvk.conf $PREFIX/glibc/opt
	fi

	for i in $PREFIX/glibc/opt/conf/*.conf; do
		. "$i" &>/dev/null
	done
	for i in $PREFIX/glibc/opt/conf/dynarec/*.conf; do
		. "$i" &>/dev/null
	done

	if [[ ! "$WINE_PATH" = *"wine-ge-custom-8-25"* ]] || [ ! -e "$WINE_PATH" ]; then
		unset WINEESYNC
		unset WINEESYNC_TERMUX
	fi

	case "$DEBUG_MODE" in
	0)
		export MESA_NO_ERROR=1
		export WINEDEBUG=-all
		export BOX64_LOG=0
		export BOX86_LOG=0
		export BOX64_NOBANNER=1
		export BOX86_NOBANNER=1
		export BOX64_SHOWSEGV=0
		export BOX86_SHOWSEGV=0
		export BOX64_DLSYM_ERROR=0
		export BOX86_DLSYM_ERROR=0
		export BOX64_DYNAREC_MISSING=0
        export BOX86_DYNAREC_MISSING=0
	;;
	1)
		export MESA_NO_ERROR=0
		unset WINEDEBUG
		export BOX64_LOG=1
		export BOX86_LOG=1
		export BOX64_NOBANNER=0
		export BOX86_NOBANNER=0
		export BOX64_SHOWSEGV=1
		export BOX86_SHOWSEGV=1
		export BOX64_DLSYM_ERROR=0
		export BOX86_DLSYM_ERROR=0
		export BOX64_DYNAREC_MISSING=1
		export BOX86_DYNAREC_MISSING=1
	;;
	2)
		export MESA_NO_ERROR=0
		export WINEDEBUG=warn+all
		export BOX64_LOG=1
		export BOX86_LOG=1
		export BOX64_NOBANNER=0
		export BOX86_NOBANNER=0
		export BOX64_SHOWSEGV=1
		export BOX86_SHOWSEGV=1
		export BOX64_DLSYM_ERROR=1
		export BOX86_DLSYM_ERROR=1
		export BOX64_DYNAREC_MISSING=1
		export BOX86_DYNAREC_MISSING=1
	;;
	3)
		export MESA_NO_ERROR=0
		export WINEDEBUG=+all
		export BOX64_LOG=1
		export BOX86_LOG=1
		export BOX64_NOBANNER=0
		export BOX86_NOBANNER=0
		export BOX64_SHOWSEGV=1
		export BOX86_SHOWSEGV=1
		export BOX64_DLSYM_ERROR=1
		export BOX86_DLSYM_ERROR=1
		export BOX64_DYNAREC_MISSING=1
		export BOX86_DYNAREC_MISSING=1
	;;
	esac
}
